version: '3'

services:
  mariadb:
    container_name: mariadb
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - volume_mariadb:/var/lib/mysql
    networks:
      - inception
    image: mariadb
  adminer:
    container_name: adminer
    init: true
    restart: always
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    volumes:
      - volume_mariadb:/var/lib/mysql
    networks:
      - inception
    depends_on:
      - mariadb
    image: adminer
  wordpress:
    container_name: wordpress
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - volume_wordpress:/srv/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    image: wordpress
  ftp:
    container_name: ftp
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - volume_wordpress:/srv/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    image: ftp
  static_webpage:
    container_name: static_webpage
    init: true
    restart: always
    build: ./requirements/bonus/static_webpage
    ports:
      - "4243:4243"
    networks:
      - inception
    image: static_webpage
  nginx:
    container_name: nginx
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - volume_wordpress:/srv/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress
    image: nginx
  redis:
    container_name: redis
    init: true
    restart: always
    build: ./requirements/bonus/redis
    networks:
      - inception
    image: redis
  grafana:
    container_name: grafana
    init: true
    restart: always
    build: ./requirements/bonus/grafana
    ports:
      - "3000:3000"
    volumes:
      - volume_grafana:/var/lib/grafana
    networks:
      - inception
    image: grafana

volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ade-rese/data/mariadb
  volume_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ade-rese/data/wordpress
  volume_grafana:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ade-rese/data/grafana

networks:
  inception:
    name: inception
    driver: bridge
