version: '3'

services:
  mariadb:
    container_name: mariadb
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    image: mariadb
  adminer:
    container_name: adminer
    init: true
    restart: always
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    depends_on:
      - mariadb
    image: adminer
  wordpress:
    container_name: wordpress
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/srv/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    image: wordpress
  ftp:
    container_name: ftp
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress:/srv/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    image: ftp
  static_webpage:
    container_name: static_webpage
    init: true
    restart: always
    build: ./requirements/bonus/static_webpage
    ports:
      - "4243:4243"
    networks:
      - inception
    image: static_webpage
  nginx:
    container_name: nginx
    init: true
    restart: always
    env_file:
      - .env
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress:/srv/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress
    image: nginx
  redis:
    container_name: redis
    init: true
    restart: always
    build: ./requirements/bonus/redis
    networks:
      - inception
    image: redis

volumes:
  mariadb:
  wordpress:

networks:
  inception:
    name: inception
    driver: bridge
